rundeckapp/grails-app/domain/rundeck/User.groovy
package rundeck


class User {
    String login
    String password
    String firstName
    String lastName
    String email
    Date dateCreated
    Date lastUpdated
    
    static mapping = {
        table "rduser"
    }
    String dashboardPref
    String filterPref
    static hasMany = [reportfilters:ReportFilter,jobfilters:ScheduledExecutionFilter,nodefilters:NodeFilter]
    static constraints={
        login(matches: '^[a-zA-Z0-9\\.@\\s_\\\\/-]+$')
        firstName(nullable:true, matches: '^[a-zA-Z0-9\\s\\.-]+$')
        lastName(nullable:true, matches: '^[a-zA-Z0-9\\s\\.-]+$')
        email(nullable:true,email: true)
        password(nullable:true)
        dashboardPref(nullable:true)
        filterPref(nullable:true)
    }
}

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
package rundeck.controllers

import com.dtolabs.client.utils.Constants
import com.dtolabs.rundeck.app.support.QueueQuery
import com.dtolabs.rundeck.app.support.ScheduledExecutionQuery
import com.dtolabs.rundeck.app.support.StoreFilterCommand
import com.dtolabs.rundeck.core.authorization.AuthContext
import com.dtolabs.rundeck.core.authorization.AuthorizationUtil
import com.dtolabs.rundeck.core.common.Framework
import com.dtolabs.rundeck.core.common.FrameworkProject
import com.dtolabs.rundeck.core.execution.service.FileCopierService
import com.dtolabs.rundeck.core.execution.service.NodeExecutorService
import com.dtolabs.rundeck.core.plugins.configuration.PropertyScope
import com.dtolabs.rundeck.core.plugins.configuration.Validator
import com.dtolabs.rundeck.plugins.storage.StorageConverterPlugin
import com.dtolabs.rundeck.plugins.storage.StoragePlugin
import com.dtolabs.rundeck.server.authorization.AuthConstants
import com.dtolabs.rundeck.server.plugins.services.StorageConverterPluginProviderService
import com.dtolabs.rundeck.server.plugins.services.StoragePluginProviderService
import grails.converters.JSON
import groovy.xml.MarkupBuilder
import rundeck.Execution
import rundeck.ScheduledExecution
import rundeck.ScheduledExecutionFilter
import rundeck.User
import rundeck.codecs.JobsXMLCodec
import rundeck.codecs.JobsYAMLCodec
import rundeck.filters.ApiRequestFilters
import rundeck.services.ApiService
import rundeck.services.ExecutionService
import rundeck.services.ExecutionServiceException
import rundeck.services.FrameworkService
import rundeck.services.LogFileStorageService
import rundeck.services.LoggingService
import rundeck.services.NotificationService
import rundeck.services.PluginService
import rundeck.services.ScheduledExecutionService
import rundeck.services.UserService

import javax.servlet.http.HttpServletResponse
import java.lang.management.ManagementFactory

class MenuController extends ControllerBase{
    FrameworkService frameworkService
    ExecutionService executionService
    UserService userService
    ScheduledExecutionService scheduledExecutionService
    NotificationService notificationService
    LoggingService LoggingService
    LogFileStorageService logFileStorageService
    StoragePluginProviderService storagePluginProviderService
    StorageConverterPluginProviderService storageConverterPluginProviderService
    PluginService pluginService
    def quartzScheduler
    def ApiService apiService
    static allowedMethods = [
            deleteJobfilter:'POST',
            storeJobfilter:'POST',
    ]
    def list = {
        def results = index(params)
        render(view:"index",model:results)
    }

    def nowrunning={ QueueQuery query->
        //find currently running executions
        
        if(params['Clear']){
            query=null
        }
        if(null!=query && !params.find{ it.key.endsWith('Filter')
        }){
            query.recentFilter="1h"
            params.recentFilter="1h"
        }
        if(!query.projFilter && params.project){
            query.projFilter=params.project
        }
        if(null!=query){
            query.configureFilter()
        }
        
        //find previous executions
        def model= executionService.queryQueue(query)
        //        System.err.println("nowrunning: "+model.nowrunning);
        model = executionService.finishQueueQuery(query,params,model)

        //include timestamp of last completed execution for the project
        Execution e=executionService.lastExecution(query.projFilter)
        model.lastExecId=e?.id
        
        User u = userService.findOrCreateUser(session.user)
        Map filterpref=[:] 
        if(u){
            filterpref= userService.parseKeyValuePref(u.filterPref)
        }
        model.boxfilters=filterpref
        return model
    }
    def queueList={QueueQuery query->
        def model= executionService.queryQueue(query)
        model = executionService.finishQueueQuery(query,params,model)
        response.setHeader(Constants.X_RUNDECK_RESULT_HEADER,"Jobs found: ${model.nowrunning.size()}")
        render(contentType:"text/xml",encoding:"UTF-8"){
            result{
                items(count:model.nowrunning.size()){
                    model.nowrunning.each{ Execution job ->
                        delegate.'item'{
                            id(job.id.toString())
                            name(job.toString())
                            url(g.createLink(controller:'execution',action:'follow',id:job.id))
                        }
                    }
                }
            }
        }
    }
    
    def nowrunningFragment = {QueueQuery query->
        def results = nowrunning(query)
        return results
    }
    def nowrunningAjax = {QueueQuery query->
        def results = nowrunning(query)
        //structure dataset for client-side event status processing
        def running= results.nowrunning.collect {
            def map = it.toMap()
            def data = [
                    status: ExecutionService.getExecutionState(it),
                    executionHref: createLink(controller: 'execution', action: 'show', absolute: true, id: it.id),
                    executionId: it.id,
                    duration: (it.dateCompleted?:new Date()).time - it.dateStarted.time
            ]
            if(!it.scheduledExecution){
                data['executionString']=map.workflow.commands[0].exec
            }else{
                data['jobName']=it.scheduledExecution.jobName
                if (it.scheduledExecution && it.scheduledExecution.totalTime >= 0 && it.scheduledExecution.execCount > 0) {
                    data['jobAverageDuration']= Math.floor(it.scheduledExecution.totalTime / it.scheduledExecution.execCount)
                }
                if (it.argString) {
                    data.jobArguments = FrameworkService.parseOptsFromString(it.argString)
                }
            }
            map + data
        }
        render( ([nowrunning:running] + results.subMap(['total','max','offset'])) as JSON)
    }
    def queueFragment = {QueueQuery query->
        def results = nowrunning(query)
        return results
    }
    
    
    def index ={
        /**
        * redirect to configured start page, or default to Run page
         */
        def startpage='home'
        if(grailsApplication.config.rundeck.gui.startpage){
            startpage=grailsApplication.config.rundeck.gui.startpage
        }
        if(params.page){
            startpage=params.page
        }
        if(!params.project){
            startpage='home'
        }else if (params.project && startpage == 'home') {
            startpage = 'jobs'
        }
        switch (startpage){
            case 'home':
                return redirect(controller: 'menu', action: 'home')
            case 'nodes':
                return redirect(controller:'framework',action:'nodes',params:[project:params.project])
            case 'run':
            case 'adhoc':
                return redirect(controller:'framework',action:'adhoc',params:[project:params.project])
            case 'jobs':
                return redirect(controller:'menu',action:'jobs', params: [project: params.project])
            case 'createJob':
                return redirect(controller:'scheduledExecution',action: 'create', params: [project: params.project])
            case 'uploadJob':
                return redirect(controller: 'scheduledExecution', action: 'upload', params: [project: params.project])
            case 'configure':
                return redirect(controller: 'menu', action: 'admin', params: [project: params.project])
            case 'history':
            case 'activity':
            case 'events':
                return redirect(controller:'reports',action:'index', params: [project: params.project])
        }
        return redirect(controller:'framework',action:'nodes', params: [project: params.project])
    }
    
    def jobs = {ScheduledExecutionQuery query ->
        
        def User u = userService.findOrCreateUser(session.user)
        if(params.size()<1 && !params.filterName && u ){
            Map filterpref = userService.parseKeyValuePref(u.filterPref)
            if(filterpref['workflows']){
                params.filterName=filterpref['workflows']
            }
        }
        if(!params.project){
            return redirect(controller: 'menu',action: 'home')
        }
        
        def results = jobsFragment(query)
        results.execQueryParams=query.asExecQueryParams()
        results.reportQueryParams=query.asReportQueryParams()

        withFormat{
            html {
                results
            }
            yaml{
                final def encoded = JobsYAMLCodec.encode(results.nextScheduled as List)
                render(text:encoded,contentType:"text/yaml",encoding:"UTF-8")
            }
            xml{
                response.setHeader(Constants.X_RUNDECK_RESULT_HEADER,"Jobs found: ${results.nextScheduled?.size()}")
                def writer = new StringWriter()
                def xml = new MarkupBuilder(writer)
                JobsXMLCodec.encodeWithBuilder(results.nextScheduled,xml)
                writer.flush()
                render(text:writer.toString(),contentType:"text/xml",encoding:"UTF-8")
            }
        }
    }
    
    def jobsFragment = {ScheduledExecutionQuery query ->
        long start=System.currentTimeMillis()
        AuthContext authContext = frameworkService.getAuthContextForSubject(session.subject)
        def usedFilter=null
        
        if(params.filterName){
            //load a named filter and create a query from it
            def User u = userService.findOrCreateUser(session.user)
            if(u){
                ScheduledExecutionFilter filter = ScheduledExecutionFilter.findByNameAndUser(params.filterName,u)
                if(filter){
                    def query2 = filter.createQuery()

rundeckapp/grails-app/views/menu/_displayConfigProps.gsp
<g:each in="${keys.sort()}" var="key">
    <div>
        <code><g:enc>${key}</g:enc>:
        <g:if test="${obscurePattern && key=~obscurePattern}">
            *****
        </g:if>
        <g:else>
            <g:enc>${map[key]}</g:enc>
        </g:else>
        </code>
    </div>
</g:each>

rundeckapp/grails-app/views/menu/_groupTree.gsp
<%--
  Created by IntelliJ IDEA.
  User: greg
  Date: Jul 9, 2008
  Time: 3:08:34 PM
  To change this template use File | Settings | File Templates.
--%>
<g:timerStart key="gtx"/>
<div class="jobGroups ${subtree?' subdirs':'topgroup'} expandComponent" ${subtree && !expanded && !(wasfiltered) ?'style="display:none"':''}>
<g:if test="${!prefix && wasfiltered && paginateParams.groupPath}">
    <div style="margin-bottom:4px">
        <g:if test="${paginateParams.groupPath.indexOf('/')>0}">
            <g:set var="uplevel" value="${paginateParams.groupPath.substring(0,paginateParams.groupPath.lastIndexOf('/'))}"/>
            <g:set var="newparams" value="${paginateParams}"/>
            %{
                newparams['groupPath']=uplevel
            }%
            <g:link controller="menu" action="jobs" class="groupname" title="Previous level" params="${newparams}">
                <i class="glyphicon glyphicon-arrow-up"></i>
                Up
            </g:link>
        </g:if>
        <g:else>
            <g:link controller="menu" action="jobs" class="groupname" title="Top level">
                <i class="glyphicon glyphicon-arrow-up"></i>
                Top
            </g:link>
        </g:else>
    </div>
</g:if>
<g:set var="gkeys" value="${g.sortGroupKeys(groups: jobgroups.grep {it.key != ''})}"/>
<g:timerEnd key="gtx"/>
<g:set var="prevkey" value="${null}"/>
<g:set var="indent" value="${0}"/>
<g:set var="divcounts" value="${0}"/>
<g:set var="level" value="${[]}"/>

<g:each in="${gkeys}" var="group">
    <g:timerStart key="_groupTree2.gsp-loop"/>
    <g:timerStart key="prepare"/>
    <g:set var="displaygroup" value="${group.key}"/>
    <g:set var="currkey" value="${g.rkey()}"/>
    <g:if test="${prevkey && group.key.startsWith(prevkey+'/')}">
        %{
            indent++;
            level<<group.key
        }%
        <g:set var="displaygroup" value="${group.key.substring(prevkey.length()+1)}"/>
    </g:if>
    <g:elseif test="${level && level.findLastIndexOf {group.key.startsWith(it+'/')}>=0}">
        <g:set var="found" value="${level.findLastIndexOf{group.key.startsWith(it+'/')}}"/>
        <g:set var="count" value="${level.size()-(found+1)}"/>
        <g:set var="displaygroup" value="${group.key.substring(level[found].length()+1)}"/>
        <g:set var="outdiv" value=""/>
        %{
            indent-=count;
            level = level[0..found];
            level<<group.key;
            outdiv= (['</div>'] * (count*2)).join('<!-- x -->');
            divcounts-=(count*2);
         }%
        <g:enc raw="true">${outdiv}</g:enc>

    </g:elseif>
    <g:else>
        <g:enc raw="true">${(['</div>'] * divcounts).join('<!--rend-->')}</g:enc>
        <g:set var="level" value="${[]}"/>
        <g:set var="indent" value="${0}"/>
        <g:set var="divcounts" value="${0}"/>
        %{
            level<<group.key
        }%
    </g:else>
    <g:set var="prevkey" value="${group.key}"/>
    <g:set var="groupopen" value="${(wasfiltered || jscallback || level.size()==1)}"/>
    ${"<"}div class="expandComponentHolder ${groupopen ? 'expanded' : ''} " ${">"}
        %{divcounts++;}%
        <div style="margin-bottom:4px;">
        <g:if test="${jscallback}">
            <span class="expandComponentControl textbtn action groupname jobgroupexpand"
                  title="Select this group"
                onclick="groupChosen('${enc(js:prefix ? prefix + '/' + group.key : group.key)}'); return false;"
                style="padding-left:4px;"><%--
            --%> <g:enc>${displaygroup}</g:enc><%--
        --%></span>
        </g:if>
        <g:else>
            <g:set var="jsfunc" value="Expander.toggle(this,null,'.expandComponentHolder.sub_${currkey}_group');"/>
            <g:expander open="${groupopen?'true':'false'}" jsfunc="${jsfunc}" imgfirst="true" style="padding-left:4px;" classnames="jobgroupexpand textbtn-secondary">
                <span class="foldertoggle">&nbsp;</span>
                <g:if test="${jobsjscallback}">
                    <g:enc>${displaygroup}</g:enc>
                </g:if>
            </g:expander>
            <g:if test="${!jobsjscallback}">
            <a class=" groupname secondary" href="${createLink(controller: 'menu', action: 'jobs', params: [project:params.project,groupPath: prefix ? prefix + '/' + group.key : group.key])}"><g:enc>${displaygroup}</g:enc></a>
            </g:if>
        </g:else>
        </div>

        <g:timerEnd key="prepare"/>
        ${"<"}div class="expandComponent sub_${currkey}_group sub_group" style="${wdgt.styleVisible(if: groupopen)}"${">"}
        %{ divcounts++;}%
        <g:if test="${jobgroups[group.key]}">
            <div class="jobGroups subjobs">
            <g:render template="jobslist" model="[hideSummary:true,jobslist:jobgroups[group.key],total:jobgroups[group.key]?.size(),nowrunning:nowrunning, clusterMap: clusterMap,nextExecutions:nextExecutions,jobauthorizations:jobauthorizations,authMap:authMap,nowrunningtotal:nowrunningtotal,max:max,offset:offset,paginateParams:paginateParams,sortEnabled:true,headers:false,wasfiltered:wasfiltered,small:small?true:false,jobsjscallback:jobsjscallback,runAuthRequired:runAuthRequired]"/>
            </div>
        </g:if>

    <g:timerEnd key="_groupTree2.gsp-loop"/>
</g:each>
    <g:enc raw="true">${(['</div>'] * divcounts).join('<!--rlast-->')}</g:enc>

    <g:if test="${currentJobs}">
        <g:timerStart key="_groupTree2.gsp-jobslist"/>
        <div>
        <g:render template="jobslist" model="[jobslist:currentJobs,total:currentJobs?.size(),nowrunning:nowrunning,nextExecutions:nextExecutions,jobauthorizations:jobauthorizations,authMap:authMap,nowrunningtotal:nowrunningtotal,max:max,offset:offset,paginateParams:paginateParams,sortEnabled:true,headers:false,wasfiltered:wasfiltered,small:small?true:false,jobsjscallback:jobsjscallback,runAuthRequired:runAuthRequired]"/>
        </div>
        <g:timerEnd key="_groupTree2.gsp-jobslist"/>
    </g:if>
</div>

rundeckapp/grails-app/views/menu/_workflowsMinimal.gsp
<%--
 Copyright 2010 DTO Labs, Inc. (http://dtolabs.com)

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 --%>
<%--
    _workflowsMinimal.gsp
    
    Author: Greg Schueler <a href="mailto:greg@dtosolutions.com">greg@dtosolutions.com</a>
    Created: Feb 9, 2010 11:16:06 AM
    $Id$
 --%>

<table cellspacing="0" cellpadding="0" width="100%" >
    <tr>

        <td style="text-align:left;vertical-align:top;width:200px;display:none;" id="filter" >

        </td>
        <td style="text-align:left;vertical-align:top;" id="wfcontent">


            <span id="busy" style="display:none"></span>

            <g:if test="${ groupTree}">
                <g:render template="groupTree" model="${[small:true,groupTree:groupTree.subs,currentJobs:groupTree['jobs']?groupTree['jobs']:[],wasfiltered:wasfiltered?true:false,nowrunning:nowrunning,nextExecutions:nextExecutions,authMap:authMap,nowrunningtotal:nowrunningtotal,max:max,offset:offset,paginateParams:paginateParams,sortEnabled:true]}"/>
            </g:if>
        </td>
    </tr>
</table>

rundeckapp/grails-app/views/menu/home.gsp
<%--
  Created by IntelliJ IDEA.
  User: greg
  Date: 10/4/13
  Time: 10:23 AM
  To change this template use File | Settings | File Templates.
--%>

<%@ page import="grails.converters.JSON; com.dtolabs.rundeck.server.authorization.AuthConstants" contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <g:set var="appTitle" value="${grailsApplication.config.rundeck.gui.title ?: g.message(code: 'main.app.name')}"/>
    <meta name="layout" content="base"/>
    <meta name="tabpage" content="home"/>
    <title><g:enc>${appTitle}</g:enc></title>

</head>
<body>

<div class="row">
<div class="col-sm-12">
    <g:render template="/common/messages"/>
</div>
</div>
<g:if test="${projCount>0}">
<div class="row row-space">

    <div class="col-sm-4">
        <span class="h3 text-muted">
            <g:enc>${projCount}</g:enc>
            <g:plural code="Project" count="${projCount}" textOnly="${true}"/>
        </span>
    </div>

<div class="col-sm-4">
    <g:if test="${projCount > 1}">
    %{--app summary info--}%
                <span class="h4">
                    <span class="summary-count ${execCount > 0 ? 'text-info' : 'text-muted'}"><g:enc>${execCount}</g:enc></span>
                    <strong>
                        <g:plural code="Execution" count="${execCount}" textOnly="${true}"/>
                    </strong>
                    In the last day
                </span>
                <g:if test="${projectSummaries.size() > 0}">
                    <div>
                        in
                        <span class="text-info">
                            <g:enc>${projectSummary.size()}</g:enc>
                        </span>


                        <g:plural code="Project" count="${projectSummary.size()}" textOnly="${true}"/>:
                        <g:each var="project" in="${projectSummary.sort()}" status="i">
                            <g:link action="index" controller="menu" params="[project: project]">
                                <g:enc>${project}</g:enc></g:link><g:if test="${i < projectSummary.size() - 1}">,</g:if>
                        </g:each>
                    </div>
                </g:if>
                <div>
                    <g:if test="${userCount > 0}">
                        by
                        <span class="text-info">
                            <g:enc>${userCount}</g:enc>
                        </span>
                        <g:plural code="user" count="${userCount}" textOnly="${true}"/>:
                        <g:each in="${userSummary}" var="user" status="i">
                            <g:enc>${user}</g:enc><g:if test="${i < userSummary.size() - 1}">,</g:if>
                        </g:each>
                    </g:if>
                </div>
    </g:if>
</div>
    <auth:resourceAllowed action="create" kind="project" context="application">
        <div class="col-sm-4">
            <g:link controller="framework" action="createProject" class="btn  btn-success pull-right">
                New Project
                <b class="glyphicon glyphicon-plus"></b>
            </g:link>
        </div>
    </auth:resourceAllowed>
</div>
</g:if>
<g:if test="${!projCount}">
<div class="row row-space">
<div class="col-sm-12">
    <auth:resourceAllowed action="create" kind="project" context="application" has="false">
        <div class="well">
            <g:set var="roles" value="${request.subject?.getPrincipals(com.dtolabs.rundeck.core.authentication.Group.class)?.collect { it.name }?.join(", ")}"/>
            <h2 class="text-warning">
                <g:message code="no.authorized.access.to.projects" />
            </h2>
            <p>
            <g:message code="no.authorized.access.to.projects.contact.your.administrator.user.roles.0" args="[roles]" />
            </p>
        </div>
    </auth:resourceAllowed>
    <auth:resourceAllowed action="create" kind="project" context="application" has="true">
        <div class="jumbotron">
            <g:set var="appTitle"
                   value="${grailsApplication.config.rundeck.gui.title ?: g.message(code: 'main.app.name')}"/>
            <h1>Welcome to <g:enc>${appTitle}</g:enc></h1>

            <p>
                To get started, create a new project.
            </p>
            <p>
                <g:link controller="framework" action="createProject" class="btn  btn-success btn-lg ">
                    New Project
                    <b class="glyphicon glyphicon-plus"></b>
                </g:link>
            </p>
        </div>
    </auth:resourceAllowed>
</div>
</div>
</g:if>


<div class="row row-space">
    <div class="col-sm-12">
    <div class="list-group">
        <g:each in="${projectSummaries.sort{a,b->a.key<=>b.key}}" var="projectData">
            <g:set var="project" value="${projectData.key}"/>
            <g:set var="data" value="${projectData.value}"/>
%{--Template for project details--}%
<div class="list-group-item">
            <div class="row">
                <div class="col-sm-6 col-md-4">
                    <g:link action="index" controller="menu" params="[project: project]" class="h3">
                        <i class="glyphicon glyphicon-tasks"></i>
                        <g:enc>${project}</g:enc></g:link>

                    <g:if test="${data.description}">
                        <span class="text-muted"><g:enc>${data.description}</g:enc></span>
                    </g:if>
                </div>

                <div class="clearfix visible-sm"></div>
                <div class="col-sm-6 col-md-4">
                    <a class="h4 ${data.execCount > 0 ? '' : 'text-muted'}"
                       href="${g.createLink(controller: "reports", action: "index", params: [project: project])}"

                    >
                        <span class="summary-count ${data.execCount > 0 ? 'text-info' : '' }"><g:enc>${data.execCount}</g:enc></span>
                        <strong>
                            <g:plural code="Execution" count="${data.execCount}" textOnly="${true}"/>
                        </strong>
                        In the last day
                    </a>
                    <div>
                        <g:if test="${data.userCount>0}">
                        by
                        <span class="text-info">
                        <g:enc>${data.userCount}</g:enc>
                        </span>

                            <g:plural code="user" count="${data.userCount}" textOnly="${true}"/>:

                            <g:each in="${data.userSummary}" var="user" status="i">
                                <g:enc>${user}</g:enc><g:if test="${i < data.userSummary.size() - 1}">,</g:if>
                            </g:each>
                        </g:if>
                    </div>
                </div>



                <div class="clearfix visible-xs visible-sm"></div>
                <g:if test="${data.auth?.jobCreate || data.auth?.admin}">
                    <div class="col-sm-12 col-md-4">
                    <div class="pull-right">
                        <g:if test="${data.auth?.admin}">
                            <a href="${g.createLink(controller: "menu", action: "admin", params: [project: project])}"
                               class="btn btn-default btn-sm">
                                <g:message code="gui.menu.Admin"/>
                            </a>
                        </g:if>
                        <div class="btn-group ">

                            <g:if test="${data.auth.jobCreate}">
                            <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                                Create <g:message code="domain.ScheduledExecution.title"/>
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li><a href="${g.createLink(controller: "scheduledExecution", action: "create", params: [project: project])}">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    New <g:message
                                        code="domain.ScheduledExecution.title"/>&hellip;

                                </a>
                                </li>
                                <li class="divider">
                                </li>
                                <li>
                                    <a href="${g.createLink(controller: "scheduledExecution", action: "upload", params: [project: project])}"
                                       class="">
                                        <i class="glyphicon glyphicon-upload"></i>
                                        Upload Definition&hellip;
                                    </a>
                                </li>
                            </ul>
                            </g:if>
                        </div>
                        </div>
                    </div>
                </g:if>
            </div>

        <g:if test="${data.readme?.readme || data.readme?.motd}">
            <div class="row row-space">
                <div class="col-sm-12">
                    <g:if test="${data.readme?.motd}">
                        %{--Test if user has dismissed the motd for this project--}%
                        <div class="">
                            <g:if test="${data.readme.motd && data.readme.readme}">
                            </g:if>
                            <g:if test="${data.readme.motdHTML}">
                                <g:enc raw="true">${data.readme.motdHTML}</g:enc>
                            </g:if>
                            <g:elseif test="${data.readme.motd}">
                                <g:enc>${data.readme.motd}</g:enc>
                            </g:elseif>
                        </div>
                    </g:if>
                    <g:if test="${data.readme?.readme}">
                        <g:if test="${data.readme.readmeHTML}">
                            <g:enc raw="true">${data.readme.readmeHTML}</g:enc>
                        </g:if>
                        <g:elseif test="${data.readme.readme}">
                            <g:enc>${data.readme.readme}</g:enc>
                        </g:elseif>

                    </g:if>

                </div>
            </div>
        </g:if>
</div>

</g:each>
    </div>
    </div>
</div>

</body>
</html>

rundeckapp/grails-app/views/menu/jobsPicker.gsp
<g:if test="${ jobgroups}">
    <g:render template="groupTree" model="${[small:params.compact?true:false,jobgroups:jobgroups,currentJobs:jobgroups['']?jobgroups['']:[],wasfiltered:wasfiltered?true:false,jobauthorizations:jobauthorizations,nowrunning:nowrunning,nextExecutions:nextExecutions,authMap:authMap,nowrunningtotal:nowrunningtotal,max:max,offset:offset,paginateParams:paginateParams,sortEnabled:true,jobsjscallback:jobsjscallback,runAuthRequired:runAuthRequired]}"/>
</g:if>

rundeckapp/grails-app/views/menu/metrics.gsp
<%--
  Created by IntelliJ IDEA.
  User: greg
  Date: 10/3/13
  Time: 12:19 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="base"/>
    <meta name="meta.tabpage" content="configure"/>
    <title>Metrics Links</title>
</head>
<body>

<div class="row">
    <div class="col-sm-3">
        <g:render template="configNav" model="[selected: 'metrics']"/>
    </div>

    <div class="col-sm-9">
<g:markdown>
* [Metrics](${g.createLink(uri: '/metrics/metrics?pretty=true')}) (json)
* [Ping](${g.createLink(uri:'/metrics/ping')})
* [Threads](${g.createLink(uri: '/metrics/threads')})
* [Healthcheck](${g.createLink(uri: '/metrics/healthcheck')})  (json)
</g:markdown>
        </div>
    </div>

</body>
</html>

rundeckapp/grails-app/views/menu/nowrunningFragment.gsp
<g:set var="rkey" value="${g.rkey()}" />
<g:render template="runningExecutions" model="[executions:nowrunning,jobs:jobs,nowrunning:true,idprefix:rkey,emptyText:'']"/>
    <g:if test="${total && max && total.toInteger() > max.toInteger()}">
        <span class="info note">Showing <g:enc>${nowrunning.size()}of ${total}</g:enc></span>
    </g:if>
<g:if test="${total>max}">
<span class="paginate"><g:paginate action="nowrunning" total="${total}"  max="${max}"/></span>
</g:if>
<g:render template="/common/boxinfo" model="${[name:'nowrunning',model:[title:'Now Running',total:total,lastExecId:lastExecId]]}"/>